name: build

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        lazarus-versions: [stable, 2.0.12]
    steps:
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - uses: actions/checkout@v2
    - name: Build the Main Application
      run: lazbuild -B --bm="Release" "consopool.lpi"
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.operating-system }}
        path: |
          consopool
          consopool.exe
  package-release:
    if: contains(github.ref, '/tags/')
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: List everything
        run: |
          ls -al
          ls -al windows-latest
          ls -al ubuntu-latest
      - name: Package Windows
        run: |
          cp windows-latest/consopool.exe .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          zip consopool-${tag}-x86_64-win64.zip consopool.exe
      - name: Package Linux
        run: |
          cp ubuntu-latest/consopool .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          chmod +x consopool
          tar -zcvf consopool-${tag}-x86_64-linux.tar.gz consopool
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            consopool-*.zip
            consopool-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
